use_frameworks!

platform :ios, '9.0'

target 'BaseViewControllerSwift_Example' do
  pod 'BaseViewControllerSwift', :path => '../'

  target 'BaseViewControllerSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
